### ISSUE TITLE
make "last_image" 1024x768 for all cam uploads

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#69]

**Comment by gdunstone** [comment]
fixed in https://github.com/borevitzlab/spc-eyepi/commit/0fc4fc3c3f215bf3749144da6121a7caad6efc7b

**Comment by TimeScience** [comment]
not fixed....

![image](https://cloud.githubusercontent.com/assets/3067588/20129682/adfa3be2-a6a5-11e6-8bbc-499705e09572.png)

**Comment by gdunstone** [comment]
It is fixed. I just havent pushed the changes to that raspberry pi.

**Comment by mohammades303** [comment]
Isn't it better to resize them to "1080x720" so that aspect ratio is intact?

**Comment by TimeScience** [comment]
it is not fixed until it is in production :)
​

**Comment by gdunstone** [comment]
@mohammades303 told me its best to do 1080x720

**Comment by gdunstone** [comment]
the production images are now doing 1080x720
